## Basic Configuration

baseurl = "https://shahe101.github.io" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Shahe Papissian"
title = "Shahe Papissian"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Shahe Papissian"
intro = "Software Developer"
description = "Previously @Bridgewater Associates and @Mitsubishi Heavy Industries.<br/>Bachelor of Computer Science @University of Waterloo."
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Personal Website"
keywords = "shahe,papissian,bridgewater,mitsubishi,devops,software,engineer,waterloo"

## Social Accounts
[params.social]
github = "shahe101"
linkedin = "papissian"
email = "shahe.papissian@gmail.com"

## Extras
[params.extra]
copyright = "© 2017. Shahe Papissian." 
poweredby = false
highlightjs = true

## Main Menu
[[menu.main]]
    name = "resume"
    identifier = "resume"
    weight = 100
    url = "/resume/"
